name: series_plot
description: An absolute bare-bones web app.
version: 0.0.1
#homepage: https://www.example.com
#author: teja <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  grizzly_series: ^0.2.0
  grizzly_plotly: ^0.2.1-dev
  plotly:

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

web:
  compiler:
    debug: dartdevc