name: series_plot
description: Demo application showcasing plotting and visualization of Grizzly Series
version: 0.0.1
homepage: https://github.com/tejainece/series_plot
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  grizzly_series: ^0.2.0
  grizzly_plotly: ^0.2.1-dev
  plotly:

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

web:
  compiler:
    debug: dartdevc